import dotenv from "dotenv";
dotenv.config();

export const settings = Object.freeze({
  LLM_PROVIDER: process.env.LLM_PROVIDER ?? "openai",
  LLM_API_KEY: process.env.LLM_API_KEY ?? "",
  LLM_BASE_URL: process.env.LLM_BASE_URL ?? "https://api.minimax.chat/v1",
  LLM_MODEL: process.env.LLM_MODEL ?? "MiniMax-M2.7",
  LLM_LIGHT_MODEL: process.env.LLM_LIGHT_MODEL ?? "glm-4.7",
  LLM_TEMPERATURE: parseFloat(process.env.LLM_TEMPERATURE ?? "0.7"),
  LLM_TEMPERATURE_STRUCTURED: parseFloat(process.env.LLM_TEMPERATURE_STRUCTURED ?? "0.1"),
  LLM_TEMPERATURE_CREATIVE: parseFloat(process.env.LLM_TEMPERATURE_CREATIVE ?? "0.7"),
  LLM_TEMPERATURE_CHAT: parseFloat(process.env.LLM_TEMPERATURE_CHAT ?? "0.6"),
  LLM_MAX_TOKENS: parseInt(process.env.LLM_MAX_TOKENS ?? "4096", 10),
  LLM_MAX_TOKENS_PLAN: parseInt(process.env.LLM_MAX_TOKENS_PLAN ?? "8192", 10),
  SESSION_STORE_TYPE: process.env.SESSION_STORE_TYPE ?? "memory",
  SESSION_STORE_PATH: process.env.SESSION_STORE_PATH ?? "",
  BUDGET_MAX_RETRIES: parseInt(process.env.BUDGET_MAX_RETRIES ?? "3", 10),
  PARALLEL_TIMEOUT: parseInt(process.env.PARALLEL_TIMEOUT ?? "30", 10),
  API_HOST: process.env.API_HOST ?? "0.0.0.0",
  API_PORT: parseInt(process.env.API_PORT ?? "3000", 10),
  LOG_LEVEL: process.env.LOG_LEVEL ?? "info",
  RAPIDAPI_KEY: process.env.RAPIDAPI_KEY ?? "",
  RAPIDAPI_HOST: process.env.RAPIDAPI_HOST ?? "booking-com15.p.rapidapi.com",
  AMAP_API_KEY: process.env.AMAP_API_KEY ?? "",
  SESSION_TTL_MS: parseInt(process.env.SESSION_TTL_MS ?? "7200000", 10),
  MAX_CONVERSATION_TURNS: parseInt(process.env.MAX_CONVERSATION_TURNS ?? "20", 10),
  MAX_GATHERING_TURNS: parseInt(process.env.MAX_GATHERING_TURNS ?? "6", 10),
  SEARCH_TIMEOUT_MS: parseInt(process.env.SEARCH_TIMEOUT_MS ?? "10000", 10),
  MAX_TRANSPORT_OPTIONS: parseInt(process.env.MAX_TRANSPORT_OPTIONS ?? "4", 10),
  MAX_HOTEL_OPTIONS: parseInt(process.env.MAX_HOTEL_OPTIONS ?? "3", 10),
  WEBSEARCH_DAEMON_URL: process.env.WEBSEARCH_DAEMON_URL ?? "http://127.0.0.1:3210",
  FIRECRAWL_API_KEY: process.env.FIRECRAWL_API_KEY ?? "",
  FIRECRAWL_ENABLED: process.env.FIRECRAWL_ENABLED !== "false",
  XHS_SERVICE_URL: process.env.XHS_SERVICE_URL ?? "http://127.0.0.1:3220",
  TRAIN_12306_ENABLED: process.env.TRAIN_12306_ENABLED !== "false",
  RAG_ENABLED: process.env.RAG_ENABLED !== "false",
  RAG_CHROMA_URL: process.env.RAG_CHROMA_URL ?? "",
  RAG_EMBEDDING_API_KEY: process.env.RAG_EMBEDDING_API_KEY ?? process.env.LLM_API_KEY ?? "",
  RAG_EMBEDDING_BASE_URL: process.env.RAG_EMBEDDING_BASE_URL ?? process.env.LLM_BASE_URL ?? "",
  RAG_EMBEDDING_MODEL: process.env.RAG_EMBEDDING_MODEL ?? "text-embedding-3-small",
  RAG_PDF_DIR: process.env.RAG_PDF_DIR ?? "",
});
